# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-20 03:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Backup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('droplet_id', models.IntegerField()),
                ('droplet_name', models.CharField(max_length=180, verbose_name='droplet name')),
                ('droplet_backup_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
